#!/usr/bin/env bash
# Interactive setup for git identities.
# Prompts for personal + N work identities and generates:
#   ~/.gitconfig.local          — [includeIf] rules (one per directory)
#   ~/.gitconfig-personal       — personal user/email/GPG
#   ~/.gitconfig-work-<slug>    — one file per work identity
#
# Safe to re-run — detects existing identities and only adds new ones.
set -euo pipefail

MARKER="# Generated by dotfiles/scripts/setup-identities.sh — do not edit manually"
GITCONFIG_LOCAL="$HOME/.gitconfig.local"
GITCONFIG_PERSONAL="$HOME/.gitconfig-personal"
PERSONAL_DIR="~/projects/"

# ── helpers ──────────────────────────────────────────────────────────────────

ask() {
  # ask <variable_name> <prompt> [default]
  local __var="$1"
  local label="$2"
  local default="${3:-}"
  local value

  if [[ -n "$default" ]]; then
    read -rp "  $label [$default]: " value
    printf -v "$__var" '%s' "${value:-$default}"
  else
    while true; do
      read -rp "  $label: " value
      [[ -n "$value" ]] && break
      echo "  (cannot be empty)"
    done
    printf -v "$__var" '%s' "$value"
  fi
}

ask_optional() {
  # ask_optional <variable_name> <prompt> [default]
  local __var="$1"
  local label="$2"
  local default="${3:-}"
  local value
  if [[ -n "$default" ]]; then
    read -rp "  $label [$default]: " value
    printf -v "$__var" '%s' "${value:-$default}"
  else
    read -rp "  $label (leave blank to skip): " value
    printf -v "$__var" '%s' "$value"
  fi
}

show_gpg_keys() {
  if ! command -v gpg &>/dev/null; then return; fi
  local out
  out=$(gpg --list-secret-keys --keyid-format LONG 2>/dev/null \
    | awk '
        /^sec/  { split($2, a, "/"); key = a[2] }
        /^\s*[0-9A-F]{40}/ { next }
        /^uid/  { sub(/^\[.*\] /, "", $0); sub(/^uid[[:space:]]+/, "", $0); print "    " key "  " $0 }
      ' || true)
  if [[ -n "$out" ]]; then
    echo ""
    echo "  Available GPG secret keys:"
    echo "$out"
    echo ""
  fi
}

write_identity() {
  local file="$1"
  local name="$2"
  local email="$3"
  local key="$4"   # may be empty

  {
    echo "$MARKER"
    echo ""
    echo "[user]"
    echo "    name  = $name"
    echo "    email = $email"
    if [[ -n "$key" ]]; then
      echo "    signingkey = $key"
      echo ""
      echo "[commit]"
      echo "    gpgsign = true"
      echo ""
      echo "[tag]"
      echo "    gpgsign = true"
    fi
  } > "$file"

  echo "    $file"
}

normalize_dir() {
  # Ensure the directory ends with / for gitdir matching
  local dir="${1%/}/"
  echo "$dir"
}

read_identity_file() {
  # read_identity_file <file> <name_var> <email_var> <key_var>
  local file="$1"
  local __name_var="$2"
  local __email_var="$3"
  local __key_var="$4"
  printf -v "$__name_var"  '%s' "$(git config --file "$file" user.name       2>/dev/null || echo "")"
  printf -v "$__email_var" '%s' "$(git config --file "$file" user.email      2>/dev/null || echo "")"
  printf -v "$__key_var"   '%s' "$(git config --file "$file" user.signingkey 2>/dev/null || echo "")"
}

local_has_entry() {
  # Returns true if .gitconfig.local already contains an includeIf for the given dir
  [[ -f "$GITCONFIG_LOCAL" ]] && grep -qF "gitdir:$1" "$GITCONFIG_LOCAL"
}

find_first_repo() {
  # Find the first git repo under a directory at any depth.
  # -prune stops find from descending into .git dirs themselves.
  local dir="$1"
  local hit
  hit=$(find "$dir" -name ".git" -type d -prune 2>/dev/null | head -1)
  [[ -n "$hit" ]] && dirname "$hit" || echo ""
}

check_identity() {
  # check_identity <label> <expanded-dir>
  local label="$1"
  local dir="$2"
  local repo
  repo=$(find_first_repo "$dir")
  echo -n "    $label  →  "
  if [[ -n "$repo" ]]; then
    git -C "$repo" config user.email 2>/dev/null || echo "(identity not resolved in $repo)"
  else
    echo "(no repos found yet — identity will apply once you clone one)"
  fi
}

append_local_entry() {
  local dir="$1"
  local file="$2"
  {
    echo ""
    echo "[includeIf \"gitdir:$dir\"]"
    echo "    path = $file"
  } >> "$GITCONFIG_LOCAL"
}

# ── main ─────────────────────────────────────────────────────────────────────

echo ""
echo "==> Git identity setup"
echo "────────────────────────────────────────────────────────────"

show_gpg_keys

# ── personal identity ─────────────────────────────────────────────────────────
echo "── Personal identity (applied inside ~/projects/) ──"
echo ""

PERSONAL_NAME=""
PERSONAL_EMAIL=""
PERSONAL_KEY=""
UPDATE_PERSONAL=true

if [[ -f "$GITCONFIG_PERSONAL" ]]; then
  read_identity_file "$GITCONFIG_PERSONAL" PERSONAL_NAME PERSONAL_EMAIL PERSONAL_KEY
  echo "  Existing personal identity:"
  echo "    Name:  $PERSONAL_NAME"
  echo "    Email: $PERSONAL_EMAIL"
  [[ -n "$PERSONAL_KEY" ]] && echo "    GPG:   $PERSONAL_KEY"
  echo ""
  read -rp "  Update personal identity? [y/N]: " _ans
  [[ "${_ans,,}" == "y" ]] || UPDATE_PERSONAL=false
  echo ""
fi

if $UPDATE_PERSONAL; then
  ask          PERSONAL_NAME  "Full name"          "$PERSONAL_NAME"
  ask          PERSONAL_EMAIL "Email"              "$PERSONAL_EMAIL"
  ask_optional PERSONAL_KEY   "GPG signing key ID" "$PERSONAL_KEY"
  echo ""
fi

# ── work identities ───────────────────────────────────────────────────────────
echo "── Work identities ──"
echo ""

# Parse existing work identity entries from .gitconfig.local
declare -a EXISTING_WORK_DIRS=()
declare -a EXISTING_WORK_CONFIGS=()

if [[ -f "$GITCONFIG_LOCAL" ]]; then
  _current_dir=""
  while IFS= read -r _line; do
    if [[ "$_line" =~ \[includeIf[[:space:]]+\"gitdir:([^\"]+)\"\] ]]; then
      _current_dir="${BASH_REMATCH[1]}"
    elif [[ "$_line" =~ ^[[:space:]]*path[[:space:]]*=[[:space:]]*(.*) && -n "$_current_dir" ]]; then
      _cfg="${BASH_REMATCH[1]}"
      if [[ "$_current_dir" != "$PERSONAL_DIR" ]]; then
        EXISTING_WORK_DIRS+=("$_current_dir")
        EXISTING_WORK_CONFIGS+=("$_cfg")
      fi
      _current_dir=""
    fi
  done < "$GITCONFIG_LOCAL"
fi

if [[ ${#EXISTING_WORK_DIRS[@]} -gt 0 ]]; then
  echo "  Existing work identities (kept as-is):"
  for (( _i=0; _i<${#EXISTING_WORK_DIRS[@]}; _i++ )); do
    echo "    ${EXISTING_WORK_DIRS[$_i]}  →  ${EXISTING_WORK_CONFIGS[$_i]}"
  done
  echo ""
fi

declare -a WORK_DIRS=()
declare -a WORK_FILES=()
declare -a WORK_NAMES=()
declare -a WORK_EMAILS=()
declare -a WORK_KEYS=()

read -rp "  How many new work identities to add? [0]: " work_count
work_count="${work_count:-0}"

for (( i=1; i<=work_count; i++ )); do
  echo ""
  echo "  Work identity $i:"
  ask      WORK_DIR   "Directory (e.g. ~/work/client1)"
  ask      WORK_NAME  "Full name"
  ask      WORK_EMAIL "Email"
  ask      WORK_SLUG  "Config file suffix (e.g. client1)"
  ask_optional WORK_KEY "GPG signing key ID"

  WORK_DIR=$(normalize_dir "$WORK_DIR")
  WORK_FILE="$HOME/.gitconfig-work-$WORK_SLUG"

  WORK_DIRS+=("$WORK_DIR")
  WORK_FILES+=("$WORK_FILE")
  WORK_NAMES+=("$WORK_NAME")
  WORK_EMAILS+=("$WORK_EMAIL")
  WORK_KEYS+=("$WORK_KEY")
done

# ── write files ───────────────────────────────────────────────────────────────
echo ""
echo "==> Writing identity files..."

if $UPDATE_PERSONAL; then
  write_identity "$GITCONFIG_PERSONAL" "$PERSONAL_NAME" "$PERSONAL_EMAIL" "$PERSONAL_KEY"
else
  echo "    $GITCONFIG_PERSONAL (unchanged)"
fi

for (( i=0; i<${#WORK_FILES[@]}; i++ )); do
  write_identity "${WORK_FILES[$i]}" "${WORK_NAMES[$i]}" "${WORK_EMAILS[$i]}" "${WORK_KEYS[$i]}"
done

# ── update ~/.gitconfig.local ─────────────────────────────────────────────────
echo ""
echo "==> Updating ~/.gitconfig.local..."

if [[ ! -f "$GITCONFIG_LOCAL" ]]; then
  {
    echo "$MARKER"
    echo ""
    echo "[includeIf \"gitdir:$PERSONAL_DIR\"]"
    echo "    path = $GITCONFIG_PERSONAL"
  } > "$GITCONFIG_LOCAL"
  echo "    created with personal entry"
elif ! local_has_entry "$PERSONAL_DIR"; then
  append_local_entry "$PERSONAL_DIR" "$GITCONFIG_PERSONAL"
  echo "    added personal entry"
else
  echo "    personal entry already present (unchanged)"
fi

for (( i=0; i<${#WORK_DIRS[@]}; i++ )); do
  if local_has_entry "${WORK_DIRS[$i]}"; then
    echo "    (skipped — already configured: ${WORK_DIRS[$i]})"
  else
    append_local_entry "${WORK_DIRS[$i]}" "${WORK_FILES[$i]}"
    echo "    added ${WORK_DIRS[$i]}  →  ${WORK_FILES[$i]}"
  fi
done

# ── verify ────────────────────────────────────────────────────────────────────
echo ""
echo "==> Done. Quick sanity check:"
echo ""
if [[ -d "$HOME/projects" ]]; then
  check_identity "~/projects" "$HOME/projects"
fi
for (( i=0; i<${#EXISTING_WORK_DIRS[@]}; i++ )); do
  expanded="${EXISTING_WORK_DIRS[$i]/#\~/$HOME}"
  [[ -d "$expanded" ]] && check_identity "${EXISTING_WORK_DIRS[$i]}" "$expanded"
done
for (( i=0; i<${#WORK_DIRS[@]}; i++ )); do
  expanded="${WORK_DIRS[$i]/#\~/$HOME}"
  [[ -d "$expanded" ]] && check_identity "${WORK_DIRS[$i]}" "$expanded"
done
echo ""
