#!/usr/bin/env bash
# Interactive setup for git identities.
# Prompts for personal + N work identities and generates:
#   ~/.gitconfig.local          — [includeIf] rules (one per directory)
#   ~/.gitconfig-personal       — personal user/email/GPG
#   ~/.gitconfig-work-<slug>    — one file per work identity
#
# Safe to re-run — regenerates all files from scratch.
set -euo pipefail

MARKER="# Generated by dotfiles/scripts/setup-identities.sh — do not edit manually"

# ── helpers ──────────────────────────────────────────────────────────────────

ask() {
  # ask <variable_name> <prompt> [default]
  local __var="$1"
  local label="$2"
  local default="${3:-}"
  local value

  if [[ -n "$default" ]]; then
    read -rp "  $label [$default]: " value
    printf -v "$__var" '%s' "${value:-$default}"
  else
    while true; do
      read -rp "  $label: " value
      [[ -n "$value" ]] && break
      echo "  (cannot be empty)"
    done
    printf -v "$__var" '%s' "$value"
  fi
}

ask_optional() {
  local __var="$1"
  local label="$2"
  local value
  read -rp "  $label (leave blank to skip): " value
  printf -v "$__var" '%s' "$value"
}

show_gpg_keys() {
  if ! command -v gpg &>/dev/null; then return; fi
  local out
  out=$(gpg --list-secret-keys --keyid-format LONG 2>/dev/null \
    | awk '
        /^sec/  { split($2, a, "/"); key = a[2] }
        /^\s*[0-9A-F]{40}/ { next }
        /^uid/  { sub(/^\[.*\] /, "", $0); sub(/^uid[[:space:]]+/, "", $0); print "    " key "  " $0 }
      ' || true)
  if [[ -n "$out" ]]; then
    echo ""
    echo "  Available GPG secret keys:"
    echo "$out"
    echo ""
  fi
}

write_identity() {
  local file="$1"
  local name="$2"
  local email="$3"
  local key="$4"   # may be empty

  {
    echo "$MARKER"
    echo ""
    echo "[user]"
    echo "    name  = $name"
    echo "    email = $email"
    if [[ -n "$key" ]]; then
      echo "    signingkey = $key"
      echo ""
      echo "[commit]"
      echo "    gpgsign = true"
      echo ""
      echo "[tag]"
      echo "    gpgsign = true"
    fi
  } > "$file"

  echo "    $file"
}

normalize_dir() {
  # Ensure the directory ends with / for gitdir matching
  local dir="${1%/}/"
  echo "$dir"
}

# ── main ─────────────────────────────────────────────────────────────────────

echo ""
echo "==> Git identity setup"
echo "────────────────────────────────────────────────────────────"

show_gpg_keys

# ── personal identity ─────────────────────────────────────────────────────────
echo "── Personal identity (applied inside ~/projects/) ──"
echo ""
ask PERSONAL_NAME  "Full name"
ask PERSONAL_EMAIL "Email"
ask_optional PERSONAL_KEY "GPG signing key ID"
echo ""

# ── work identities ───────────────────────────────────────────────────────────
echo "── Work identities ──"
echo ""
read -rp "  How many work identities? [0]: " work_count
work_count="${work_count:-0}"

declare -a WORK_DIRS=()
declare -a WORK_FILES=()

for (( i=1; i<=work_count; i++ )); do
  echo ""
  echo "  Work identity $i:"
  ask      WORK_DIR   "Directory (e.g. ~/work/client1)"
  ask      WORK_NAME  "Full name"
  ask      WORK_EMAIL "Email"
  ask      WORK_SLUG  "Config file suffix (e.g. client1)"
  ask_optional WORK_KEY "GPG signing key ID"

  WORK_DIR=$(normalize_dir "$WORK_DIR")
  WORK_FILE="$HOME/.gitconfig-work-$WORK_SLUG"

  WORK_DIRS+=("$WORK_DIR")
  WORK_FILES+=("$WORK_FILE")

  # Write immediately so errors surface early
  write_identity "$WORK_FILE" "$WORK_NAME" "$WORK_EMAIL" "$WORK_KEY" > /dev/null
done

# ── write files ───────────────────────────────────────────────────────────────
echo ""
echo "==> Writing identity files..."

write_identity "$HOME/.gitconfig-personal" "$PERSONAL_NAME" "$PERSONAL_EMAIL" "$PERSONAL_KEY"

for (( i=0; i<${#WORK_FILES[@]}; i++ )); do
  write_identity "${WORK_FILES[$i]}" \
    "$(grep 'name' "${WORK_FILES[$i]}" | awk -F'= ' '{print $2}')" \
    "$(grep 'email' "${WORK_FILES[$i]}" | awk -F'= ' '{print $2}')" \
    "$(grep 'signingkey' "${WORK_FILES[$i]}" 2>/dev/null | awk -F'= ' '{print $2}' || echo "")"
done

echo ""
echo "==> Writing ~/.gitconfig.local..."
{
  echo "$MARKER"
  echo ""
  echo "[includeIf \"gitdir:~/projects/\"]"
  echo "    path = ~/.gitconfig-personal"

  for (( i=0; i<${#WORK_DIRS[@]}; i++ )); do
    echo ""
    echo "[includeIf \"gitdir:${WORK_DIRS[$i]}\"]"
    echo "    path = ${WORK_FILES[$i]}"
  done
} > "$HOME/.gitconfig.local"
echo "    ~/.gitconfig.local"

# ── verify ────────────────────────────────────────────────────────────────────
echo ""
echo "==> Done. Quick sanity check:"
echo ""
if [[ -d "$HOME/projects" ]]; then
  echo -n "    ~/projects  →  "
  git -C "$HOME/projects" config user.email 2>/dev/null || echo "(no git repo there yet — identity will apply once you clone one)"
fi
for (( i=0; i<${#WORK_DIRS[@]}; i++ )); do
  expanded="${WORK_DIRS[$i]/#\~/$HOME}"
  if [[ -d "$expanded" ]]; then
    echo -n "    ${WORK_DIRS[$i]}  →  "
    git -C "$expanded" config user.email 2>/dev/null || echo "(no git repo there yet)"
  fi
done
echo ""
